### ISSUE TITLE
output rate to servos too fast in main loop

### ISSUE THREAD

**Issue by hannes-m** [nickrehm/dRehmFlight-F-35#1]
The main loop is executed with 2000 hz - every 500 microseconds...
So the output to the servos is called every 500 microseconds...
But the pulse for the servo can last up to 2000 microseconds...(I am using 700 to 2300 microseconds for a enlarged range of the aileron-servo and added also a servo-timer in the code).
There should be a seperate timer to control the output to the servos.

**Comment by nickrehm** [comment]
Servo library handles 50Hz timing. Commands pushed to it faster than that are thrown away.
