### ISSUE TITLE
SVG files

### ISSUE THREAD

**Issue by jajawunderbar** [nickrehm/dRehmFlight-F-35#2]
Hi, is it possible to get the svg or similar files to cut it in a plotter? Thanks!
(My f35 is ready and flown but I need to repair it ...)
Greetings Mathias

**Comment by RobinBennett** [comment]
Here you go:
![F-35 2](https://github.com/nickrehm/dRehmFlight-F-35/assets/61478295/b7c3dd17-ef61-4ac1-b4a0-b9e21d103c8d)
![F-35 1](https://github.com/nickrehm/dRehmFlight-F-35/assets/61478295/eae2e683-8d4a-4c22-89b9-44b2f5ec0ed6)

IIRC I used Inkscape to extract them from the PDFs

**Comment by RobinBennett** [comment]
Hmm, that didn't work - they've been cropped. Anyway, I think it's just a case of opening the PDFs in Inkscape and saving as SVG.

**Comment by jajawunderbar** [comment]
Yes i can open the pdf in inkscape, that solved it. Thanks

**Comment by jajawunderbar** [comment]
Yes i can open the pdf in inkscape, that solved it. Thanks
